### ISSUE TITLE
Bundle inheritance and method_access_control

### ISSUE THREAD

**Issue by vkartaviy** [schmittjoh/JMSSecurityExtraBundle#121]
When I am trying to inherit bundle controller `method_access_control` dosn't take into account methods of the parent controller. For example:

**config.yml**

``` yml
jms_security_extra:
    secure_all_services: false
    expressions: ~
    method_access_control:
        'FOSMessageBundle:Message:.*': hasRole("ROLE_USER")
        'AcmeMessageBundle:Message:.*': hasRole("ROLE_USER")
```

**MessageController.php**

``` php
namespace Acme\MessageBundle\Controller;

class MessageController extends \FOS\MessageBundle\Controller\MessageController
{ 
}
```

This will generate such proxy:

``` php
class MessageController extends \Acme\MessageBundle\Controller\MessageController
{
    // ...

    public function threadAction($threadId)
    {
        $ref = new \ReflectionMethod('FOS\\MessageBundle\\Controller\\MessageController', 'threadAction');
        // ...
    }

    // ...
 }
```

and interceptor:

``` php
class MessageController__JMSInjector
{
    public static function inject($container) {
        // ...
        $a = new \JMS\AopBundle\Aop\InterceptorLoader($container, array('Acme\\MessageBundle\\Controller\\MessageController' => array('threadAction' => array(0 => 'security.access.method_interceptor') /* and much more methods */)));
        // ...
    }
}
```

As you can see there is no `FOS\\MessageBundle\\Controller\\MessageController` interceptor to match the reflection  $method->class so it will be skipped.

**The expected scenario:** Interceptor should respect class inheritance.
