### ISSUE TITLE
error with Sf2.1 since friday

### ISSUE THREAD

**Issue by thibmonier** [schmittjoh/JMSSecurityExtraBundle#136]
Since update last friday with dev master version we have an error
"The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL."

We tried to debug this and no ip filters are configured in security.yml

``` YAML
jms_security_extra:
    secure_all_services: false
    expressions: true
...
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            access_denied_url: /forbidden
            form_login:
                provider: custom
                csrf_provider: form.csrf_provider
#                default_target_path: /
#                use_referer: true
                success_handler: authentication_success_handler
                failure_handler: authentication_failure_handler  
                login_path: /
                check_path:  /login_check
#                use_forward:    false
#                use_referer:    true
            fos_facebook:
                success_handler: facebook_auth_success_handler
                app_url: http://apps.facebook.com/%facebook.app_id%/
                server_url: "%facebook.server_url%"
                login_path: /
                check_path: /login_fb_check
                always_use_default_target_path: true
                use_forward:    false
                use_referer:    true
                default_target_path: /
                provider: my_fos_facebook_provider
            logout: ~

    access_control:
        - { path: ^/,roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_url%/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/%admin_url%, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
```

, but apparently, in TraceableRequestMatcher class we have line 69

``` PHP
$ips = array($this->getFieldValue('ip'));
        } else {
            $ips = $this->getFieldValue('ips');
```

Maybe you have to check if ip is not null before ?
