### ISSUE TITLE
Help with @Secure

### ISSUE THREAD

**Issue by pdias** [schmittjoh/JMSSecurityExtraBundle#156]
Hello,

I have this security.yml

´´´
security:
    encoders:
        SamlBundle\Security\User\SamlUser: plaintext

```
role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

providers:
    samlservice:
        id: saml.service.user.provider

firewalls:
    admin_saml_secured:
        pattern: ^/admin
        saml:
          route: _myipcb
        context: saml_context
        logout: true

    user_saml_secured:
        pattern: ^/utilizador
        saml:
          route: _myipcb
        context: saml_context
        logout: true

    free:
        pattern:    ^/
        anonymous:  ~
        context: saml_context

access_control:
    - { path: ^/utilizador, roles: ROLE_USER }
    - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
```

´´´

In one of my controllers i have:

´´´
use JMS\SecurityExtraBundle\Annotation\Secure;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class AdminController extends Controller
{
    /**
     \* @Secure(roles="ROLE_ADMIN")
     */
    public function indexAction()
    {
        $administration = $this->container->getParameter('administration');
        return $this->render('AdminBundle::index.html.twig', array('administration'=>$administration));
    }
}
´´´

In this controller allegedly only users with the ROLE_ADMIN could execute it, but once you've logged ... any user are able to execute this (and have only ROLE_USER).

What am I doing wrong?
