### ISSUE TITLE
method_access_control not doing anything

### ISSUE THREAD

**Issue by bvisonl** [schmittjoh/JMSSecurityExtraBundle#212]
I am cleaning up several peaces of my application and I am trying to move from having the @ PreAuthorize annotation to use the YML method.. 

I have the following configuration: 

```
jms_security_extra:
    # Enables expression language
    expressions: true

    # Actions Security
    method_access_control:
        # Dashboard
        'AppBundle:Dashboard/Dashboard:indexAction': 'hasRole("ROLE_TEST")'
```

but it's not doing anything.. I have tried to replace the Dashboard/Dashboard with Dashboard\Dashboard but still nothing.. lastly I tried to do ':indexAction$' instead of the FQCN but still nothing it let's me in right away.. 

Is there something that I am missing to configure this? It was working fine with the annotations.
